#!/bin/sh
#
# A simple script to reduce PDF file size with gs
# Original script: Alfred Klomp
# (http://www.alfredklomp.com/programming/shrinkpdf/)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Default to overwrite
OUT=${OUT:$1}

gs -sDEVICE=pdfwrite                    \
  -dCompatibilityLevel=1.4              \
  -dQUIET                               \
  -q -dNOPAUSE -dBATCH -dSAFER          \
  -dPDFSETTINGS=/screen                 \
  -dEmbedAllFonts=true                  \
  -dSubsetFonts=true                    \
  -dAutoRotatePages=/None               \
  -dColorImageDownsampleType=/Bicubic   \
  -dColorImageResolution=300            \
  -dGrayImageDownsampleType=/Bicubic    \
  -dGrayImageResolution=300             \
  -dMonoImageDownsampleType=/Bicubic    \
  -dMonoImageResolution=300             \
  -sOutputFile="/tmp/$1"                \
  "$1"

CFILE=$(stat -c%s "/tmp/$1")
OFILE=$(stat -c%s "$1")

if [[ "$OFILE" -gt "$CFILE" ]]; then
  cp "/tmp/$1" "$OUT"
else
  echo 'NOOP - Compressed file is not smaller than the original'
fi
