#!/bin/sh

# Default to overwrite
OUT=${OUT:$1}

gs -sDEVICE=pdfwrite                    \
  -dCompatibilityLevel=1.4              \
  -dQUIET                               \
  -q -dNOPAUSE -dBATCH -dSAFER          \
  -dPDFSETTINGS=/screen                 \
  -dEmbedAllFonts=true                  \
  -dSubsetFonts=true                    \
  -dAutoRotatePages=/None               \
  -dColorImageDownsampleType=/Bicubic   \
  -dColorImageResolution=300            \
  -dGrayImageDownsampleType=/Bicubic    \
  -dGrayImageResolution=300             \
  -dMonoImageDownsampleType=/Bicubic    \
  -dMonoImageResolution=300             \
  -sOutputFile="/tmp/$1"                \
  "$1"

CFILE=$(stat -c%s "/tmp/$1")
OFILE=$(stat -c%s "$1")

if [[ "$OFILE" -gt "$CFILE" ]]; then
  cp "/tmp/$1" "$OUT"
else
  echo 'NOOP - Compressed file is not smaller than the original'
fi
